//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNotes.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Notes
    {
       
        public int NoteID { get; set; }

        [Display(Name = "Assign To User")]
        public int UserID { get; set; }

        [Display(Name ="Note Content")]
        public string NoteContent { get; set; }

        [Display(Name = "Date Of Creation")]
        public System.DateTime DateOfCreation { get; set; }

        [Display(Name = "End Time")]
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
